name: ci
on:
  push: { branches: ["**"] }
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install -U pip wheel
      - run: pip install -r requirements.txt
      - run: pip install pyflakes pytest safety pip-tools cyclonedx-bom
      - name: Lint
        run: pyflakes javu_agi || true
      - name: Unit tests (critical)
        run: |
          pytest -q tests/test_immune_block.py
          pytest -q tests/test_contracts_enforce.py
          pytest -q tests/test_peace_opt.py
      - name: Full tests (allow fail fast)
        run: pytest -q tests || true
      - name: Dependency vulns
        run: safety check || true
      - name: SBOM
        run: cyclonedx-bom -o artifacts/sbom.json || true
        
name: ci
on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "main" ]
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  build-test:
    runs-on: ubuntu-22.04
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      VENDOR_ONLY_MODE: "1"
      ENABLE_SELF_LEARN: "0"
      CI: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.6.8 mypy==1.11.2 pytest==8.3.3
      - name: Lint (ruff)
        run: ruff check --output-format=github .
      - name: Format check (ruff)
        run: ruff format --check .
      - name: Type check (mypy)
        run: mypy .
      - name: Compile all
        run: python scripts/run_pycompile.py
      - name: Tests (smoke)
        run: pytest -q
      - name: Generate evidence pack
        run: python tools/generate_evidence.py
      - name: Upload evidence artifacts
        uses: actions/upload-artifact@v4
        with:
          name: evidence-pack
          path: |
            transfer_report.json
            fairness_report.json
            governance_pass_rate.json
            incident_log.json
            audit_hash_chain.txt
